### ISSUE TITLE
jdk17 org.apache.oltu.oauth2.client incompatible

### ISSUE THREAD

**Issue by zq99299** [casdoor/casdoor-spring-boot-starter#29]
implementation 'org.casbin:casdoor-spring-boot-starter:1.7.0'

<img width="1141" alt="image" src="https://user-images.githubusercontent.com/11927113/236410374-ee9c0a59-098d-4451-b260-603616299974.png">
<img width="1215" alt="image" src="https://user-images.githubusercontent.com/11927113/236410704-715e374a-5f56-47c9-9b41-641be1603089.png">
<img width="1215" alt="image" src="https://user-images.githubusercontent.com/11927113/236410996-81591940-1fa5-4482-be84-eb92346daa69.png">

As shown in the figure above, but jdk9+ has replaced javax.servlet with jakarta.servlet

In addition to this problem, the request also responds to the http status code 411, but based on the url information generated in the image above, the request can be made using other tools as normal

**Comment by zq99299** [comment]
implementation 'org.casbin:casdoor-spring-boot-starter:1.7.0'

**Comment by RanTao123** [comment]
Hi, zq99299. I found that you import oath2 packages through Gradle, but our project is all through Maven, and then you had this problem because the code of the two introduced packages was different.  You can see the file URLConnectionClient from Maven below.
![QQ图片20230629005524](https://github.com/casdoor/casdoor-spring-boot-starter/assets/65508217/c856c564-b098-4ef2-9298-e421eef24554)

**Comment by hsluoyz** [comment]
Closed as resolved
